import '../styles/globals.scss'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { CartProvider } from '../contexts/CartProvider'
import { ProductDetailsProvider } from '../contexts/ProductDetailsContext'
import productDetails from '../data/productDetails'

const App = ({Component, pageProps}: AppProps) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CartProvider cart={[]}>
        <ProductDetailsProvider product={productDetails}>
          <Component {...pageProps} />
        </ProductDetailsProvider>
      </CartProvider>
      
    </div>
  )
}

export default App
